### ISSUE TITLE
getAmountsOut() Function missing

### ISSUE THREAD

**Issue by ceds** [shanefontaine/uniswap-python#13]
I'm getting the following error when using make_trade() function:

> Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'float'>, <class 'list'>)` and keyword argument(s) of type `{}`.
> Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
> Function invocation failed due to no matching argument types.

Any ideas?

**Comment by josh-richardson** [comment]
I am also encountering this issue. Is this known to you @shanefontaine 

I am able to reproduce using Python 3.7 with the following snippet:
```
def trade_on_uniswap(symbols):
    uniswap = Uniswap("address", "private key"), version=2, max_slippage=0.1)
    
    for itm in symbols:
        symbolAddress = Web3.toChecksumAddress(symbols[itm])
        print(
            f"Uniswap allows buy of {Web3.fromWei(uniswap.get_eth_token_input_price(symbolAddress, 1 * 10 ** 18), 'ether')} {itm} for 1.0 ETH")
        uniswap.make_trade(Web3.toChecksumAddress("0x0000000000000000000000000000000000000000"), symbolAddress,
                           0.1 * 10 ** 18)
```

Where the input parameter is a simple dictionary, for example `{'MITX': '0x4a527d8fc13c5203ab24ba0944f4cb14658d1db6'}`

The output is as follows: 
```
Traceback (most recent call last):
  File "extractor.py", line 121, in <module>
    trade_on_uniswap(symbols)
  File "extractor.py", line 114, in trade_on_uniswap
    0.1 * 10 ** 18)
  File "/home/joshua/.local/share/virtualenvs/tmp.compliant.WFOq-WdoSIBqf/lib/python3.7/site-packages/uniswap/uniswap.py", line 69, in approved
    return method(self, *args)
  File "/home/joshua/.local/share/virtualenvs/tmp.compliant.WFOq-WdoSIBqf/lib/python3.7/site-packages/uniswap/uniswap.py", line 426, in make_trade
    return self._eth_to_token_swap_input(output_token, Wei(qty), recipient)
  File "/home/joshua/.local/share/virtualenvs/tmp.compliant.WFOq-WdoSIBqf/lib/python3.7/site-packages/uniswap/uniswap.py", line 485, in _eth_to_token_swap_input
    * self.get_eth_token_input_price(output_token, qty)
  File "/home/joshua/.local/share/virtualenvs/tmp.compliant.WFOq-WdoSIBqf/lib/python3.7/site-packages/uniswap/uniswap.py", line 82, in check_version
    return f(self, *args, **kwargs)
  File "/home/joshua/.local/share/virtualenvs/tmp.compliant.WFOq-WdoSIBqf/lib/python3.7/site-packages/uniswap/uniswap.py", line 294, in get_eth_token_input_price
    qty, [self.get_weth_address(), token]
  File "/home/joshua/.local/share/virtualenvs/tmp.compliant.WFOq-WdoSIBqf/lib/python3.7/site-packages/web3/contract.py", line 875, in __call__
    clone._set_function_info()
  File "/home/joshua/.local/share/virtualenvs/tmp.compliant.WFOq-WdoSIBqf/lib/python3.7/site-packages/web3/contract.py", line 885, in _set_function_info
    self.kwargs
  File "/home/joshua/.local/share/virtualenvs/tmp.compliant.WFOq-WdoSIBqf/lib/python3.7/site-packages/web3/_utils/contracts.py", line 163, in find_matching_fn_abi
    raise ValidationError(message)
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'float'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
```

Are you able to reproduce this? Thanks!

**Comment by josh-richardson** [comment]
I think this can safely be closed.

**Comment by ErikBjare** [comment]
Yeah, the Web3 error was rather clear, but understandable that it can be hard to track down if you're not aware of the internals. Closing.
