### ISSUE TITLE
Web3 Exception: Could not decode contract function call getAmountsOut return data b'' for output_types ['uint256[]']

### ISSUE THREAD

**Issue by vikramarun** [shanefontaine/uniswap-python#27]
Getting a Web3 error with the getAmountsOut error when I call the make_trade function, something with how the function is being called:

Traceback (most recent call last):
  File "C:\Users\vikra\PycharmProjects\uniswap\venv\lib\site-packages\uniswap\uniswap.py", line 69, in approved
    return method(self, *args)
  File "C:\Users\vikra\PycharmProjects\uniswap\venv\lib\site-packages\uniswap\uniswap.py", line 426, in make_trade
    return self._eth_to_token_swap_input(output_token, Wei(qty), recipient)
  File "C:\Users\vikra\PycharmProjects\uniswap\venv\lib\site-packages\uniswap\uniswap.py", line 485, in _eth_to_token_swap_input
    * self.get_eth_token_input_price(output_token, qty)
  File "C:\Users\vikra\PycharmProjects\uniswap\venv\lib\site-packages\uniswap\uniswap.py", line 82, in check_version
    return f(self, *args, **kwargs)
  File "C:\Users\vikra\PycharmProjects\uniswap\venv\lib\site-packages\uniswap\uniswap.py", line 294, in get_eth_token_input_price
    qty, [self.get_weth_address(), token]
  File "C:\Users\vikra\PycharmProjects\uniswap\venv\lib\site-packages\web3\contract.py", line 964, in call
    **self.kwargs
  File "C:\Users\vikra\PycharmProjects\uniswap\venv\lib\site-packages\web3\contract.py", line 1529, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getAmountsOut return data b'' for output_types ['uint256[]']

I'm sure the trade amount is being casted as an int -- was previously getting an error that another user had indicated where the getAmountsOut() function was missing, but this error is different.

Reproducable with the following code. Any idea what I'm doing wrong? I noticed that sometimes it works, sometimes it doesn't which makes it even more confusing. Thanks!

```
def makeTrade(contractaddress,ethamount):
    my_address = Web3.toChecksumAddress('')
    pk = ''
    uniconnect = uni.Uniswap(my_address, pk, web3=w3, version=2)
    eth = Web3.toChecksumAddress("0x0000000000000000000000000000000000000000")
    token = Web3.toChecksumAddress(contractaddress)
    tradeamount = int(ethamount*10**18)
    uniconnect.make_trade(eth, token, tradeamount)

makeTrade(contractaddress,tradesize)
```

**Comment by CryptoGnome** [comment]
I am getting this same error

**Comment by ErikBjare** [comment]
I've gotten this before as well, although never when I've ran in production. I don't remember exactly why this sometimes happens, but it could be because the token address you use isn't valid (like, for example, using a mainnet contract address on a testnet, or vice versa).

There is a testcase that is identical to your repro example (although your repro example is invalid since it lacks a valid address/privkey) and it runs fine locally for me (and in CI on my fork), so you need to provide more detail (contract address, which testnet/mainnet).

**Comment by vikramarun** [comment]
Got it to work guys -- it was as issue with the contract address I was using. Thanks. If anyone has this issue, make sure that the contract you are pointing to is a token contract (not uniswap contract)
