### ISSUE TITLE
KeyError: 'PROVIDER'

### ISSUE THREAD

**Issue by oracle707** [shanefontaine/uniswap-python#32]
I just installed Uniswap module and couldn't run simple example
I used 

>>> from uniswap import Uniswap
>>> address = "0x0000000000000000000000000000000000000000"
>>> private_key = ""
>>> uniswap_wrapper = Uniswap(address, private_key, version=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uniswap/uniswap.py", line 147, in __init__
    self.provider = provider or os.environ["PROVIDER"]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROVIDER'

**Comment by ErikBjare** [comment]
You need to set the environment variable `PROVIDER` to a Web3 provider (like Infura), or pass one to the constructor.

**Comment by oracle707** [comment]
should it be something like
$export PROVIDER = https://mainnet.infura.io/v3/projectid?

thanks
