### ISSUE TITLE
I can't run it if I change any other ecr20 token address

### ISSUE THREAD

**Issue by ztlj2015** [shanefontaine/uniswap-python#35]
Thank you for providing such a good program, but I run a little problem, please help solve it. I changed another ecr20 token address, and i can't run my program.

```py
from uniswap import Uniswap
from web3 import Web3
provide = 'https://mainnet.infura.io/v3/02c03b06ce7344d1bbde374834b349de'
address = '0xfd895ACd6960054B25Fe8CDdaA0dc271EF18716f'
private_key = '***'
uniswap_wrapper = Uniswap(address, private_key, provide, version=2)
eth = "0x0000000000000000000000000000000000000000"
pickle = Web3.toChecksumAddress("0xbd17b1ce622d73bd438b9e658aca5996dc394b0d")
print(uniswap_wrapper.get_eth_token_input_price(pickle, 1*10**18))

The error code is：
Traceback (most recent call last):
  File "D:\python\python38\lib\site-packages\web3-5.12.0-py3.8.egg\web3\contract.py", line 1509, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "D:\python\python38\lib\site-packages\eth_abi\codec.py", line 181, in decode_abi
    return decoder(stream)
  File "D:\python\python38\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "D:\python\python38\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "D:\python\python38\lib\site-packages\eth_abi\decoding.py", line 173, in decode
    yield decoder(stream)
  File "D:\python\python38\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "D:\python\python38\lib\site-packages\eth_abi\decoding.py", line 142, in decode
    start_pos = decode_uint_256(stream)
  File "D:\python\python38\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "D:\python\python38\lib\site-packages\eth_abi\decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "D:\python\python38\lib\site-packages\eth_abi\decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/workspace/python/selen/test_uniswap.py", line 13, in <module>
    print(uniswap_wrapper.get_eth_token_input_price(Web3.toChecksumAddress(pickle), 1*10**18))
  File "D:\python\python38\lib\site-packages\uniswap_python-0.4.2-py3.8.egg\uniswap\uniswap.py", line 82, in check_version
    return f(self, *args, **kwargs)
  File "D:\python\python38\lib\site-packages\uniswap_python-0.4.2-py3.8.egg\uniswap\uniswap.py", line 293, in get_eth_token_input_price
    price = self.router.functions.getAmountsOut(
  File "D:\python\python38\lib\site-packages\web3-5.12.0-py3.8.egg\web3\contract.py", line 954, in call
    return call_contract_function(
  File "D:\python\python38\lib\site-packages\web3-5.12.0-py3.8.egg\web3\contract.py", line 1532, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getAmountsOut return data b'' for output_types ['uint256[]']
```

**Comment by ztlj2015** [comment]
I don't know what's going on, it can run normally!
