### ISSUE TITLE
make_trade raises ValidationError

### ISSUE THREAD

**Issue by monk-after-90s** [shanefontaine/uniswap-python#46]
```python
...
>>>uniswap_wrapper.make_trade(eth, aave, 8e16)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/root/miniconda3/envs/paddington/lib/python3.7/site-packages/uniswap/uniswap.py", line 72, in approved
    return method(self, *args, **kwargs)
  File "/root/miniconda3/envs/paddington/lib/python3.7/site-packages/uniswap/uniswap.py", line 446, in make_trade
    return self._eth_to_token_swap_input(output_token, Wei(qty), recipient)
  File "/root/miniconda3/envs/paddington/lib/python3.7/site-packages/uniswap/uniswap.py", line 505, in _eth_to_token_swap_input
    * self.get_eth_token_input_price(output_token, qty)
  File "/root/miniconda3/envs/paddington/lib/python3.7/site-packages/uniswap/uniswap.py", line 85, in check_version
    return f(self, *args, **kwargs)
  File "/root/miniconda3/envs/paddington/lib/python3.7/site-packages/uniswap/uniswap.py", line 299, in get_eth_token_input_price
    qty, [self.get_weth_address(), token]
  File "/root/miniconda3/envs/paddington/lib/python3.7/site-packages/web3/contract.py", line 875, in __call__
    clone._set_function_info()
  File "/root/miniconda3/envs/paddington/lib/python3.7/site-packages/web3/contract.py", line 885, in _set_function_info
    self.kwargs
  File "/root/miniconda3/envs/paddington/lib/python3.7/site-packages/web3/_utils/contracts.py", line 163, in find_matching_fn_abi
    raise ValidationError(message)
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'float'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
```

**Comment by ErikBjare** [comment]
You are passing in a float as the amount. Don't do that. Use `8*10**18` instead of `8e18`.

**Comment by monk-after-90s** [comment]
> The error message is pretty clear.
> 
> You are passing in a float as the amount. Don't do that. Use `8*10**18` instead of `8e18`.

Ah, god ,I am blind. And thank you.

**Comment by monk-after-90s** [comment]
> The error message is pretty clear.
> 
> You are passing in a float as the amount. Don't do that. Use `8*10**18` instead of `8e18`.

Ah, god ,I am blind. And thank you.
