### ISSUE TITLE
Uniswap python uses net_version which appears to have been removed by recent geth

### ISSUE THREAD

**Issue by joequant** [shanefontaine/uniswap-python#54]
uniswap-python uses net_version to determine the chain, but that appears to have been removed by recent geth.  The system should use chainId to determine version

**Comment by ErikBjare** [comment]
Apparently chainId is also deprecated: https://web3py.readthedocs.io/en/stable/web3.net.html?highlight=net_version#web3.net.chainId

`eth.net.version` looks like the way to go.

**Comment by ErikBjare** [comment]
On further inspection, it looks like we're doing things right. I can't find any reference to geth removing eth_version, and it's deeply cemented in [EIP-1474](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md#net_version). 

Can you specify your geth version and the exact error you're getting?

**Comment by joequant** [comment]
```
Welcome to the Geth JavaScript console!

instance: Geth/v1.9.26-unstable-3c46f557-20201217/linux-amd64/go1.15.6
at block: 0 (Thu Jan 01 1970 00:00:00 GMT+0000 (UTC))
 datadir: /root/.ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d
```

```
Traceback (most recent call last):
  File "./test-uniswap.py", line 5, in <module>
    dfb.test_uniswap()
  File "/home/joe/local2/bench/git/sto/defibot/defibot.py", line 49, in test_uniswap
    print(self.uniswap().exchange_address_from_token(Web3.toChecksumAddress("0x2260fac5e5542a773aa44fbcfedf7c193bc2c599")))
  File "/home/joe/local2/bench/git/sto/defibot/defibot.py", line 23, in uniswap
    self._uniswap = Uniswap(self.config('address'),
  File "/home/joe/.local/lib/python3.8/site-packages/uniswap/uniswap.py", line 152, in __init__
    netid = int(self.w3.net.version)
  File "/home/joe/.local/lib/python3.8/site-packages/web3/net.py", line 44, in version
    return self._version()
  File "/home/joe/.local/lib/python3.8/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/joe/.local/lib/python3.8/site-packages/web3/manager.py", line 158, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'the method net_version does not exist/is not available'}
(base) [joe@big-apple defibot (master)]$ 
```

**Comment by joequant** [comment]
Here is the line from the log file

```
WARN [12-19|14:20:32.135] Served net_version                       conn=127.0.0.1:59362 reqid=0 t="17.98µs" err="the method net_version does not exist/is not available"
```

**Comment by joequant** [comment]
This uses web3.eth.chainId rather than web3.net.chainId

**Comment by ErikBjare** [comment]
The endpoint was mistakenly removed from geth, and was reintroduced in https://github.com/ethereum/go-ethereum/issues/22034. Closing.
