### ISSUE TITLE
Provider error

### ISSUE THREAD

**Issue by YaProstoUmniy** [shanefontaine/uniswap-python#74]
Traceback (most recent call last):
  File "X:/PARSER/unis.py", line 9, in <module>
    uniswap_wrapper = Uniswap(address, private_key,version=2)
  File "C:\Users\Opezdal\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uniswap\uniswap.py", line 147, in __init__
    self.provider = provider or os.environ["PROVIDER"]
  File "C:\Users\Opezdal\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROVIDER'

i try to remove "version",not working

**Comment by ErikBjare** [comment]
Read the README. You need to set the `PROVIDER` environment variable or pass it explicitly.
